<a href="https://colab.research.google.com/github/Epilef86/DNC/blob/main/Revis%C3%A3o_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [6]:
#array 2D, ou seja, bidimensionais

arr = np.array([[1,2,3,4,5],[6,4,7,8,9]])

print(arr)

[[1 2 3 4 5]
 [6 4 7 8 9]]


In [9]:
#array 3D, ou seja, tridimensionais

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 5 6]]]


In [11]:
#pegar o primeiro dado desse array

arr = np.array([1,2,3,4])

print(arr[2])

3


In [14]:
#operações com array

arr = np.array([[1,2,3,4,5],[6,7,8,9,4]])

print('5th elemento on 2nd row: ', arr[1,4])

5th elemento on 2nd row:  4


In [15]:
from numpy import random


In [16]:
#Gerar números aleatórios, esse randint é: traga um valor inteiro randômico(aleatório) de 0 até 100
x = random.randint(100)

print(x)


24


In [19]:
#gerar número decimal de 0 a 1
x = random.rand()

print(x)

0.06965501098996563


Operações com arrays

In [20]:
#Adição
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,54,58])

arr = np.add(arr1,arr2)

print(arr)

[30 32 34 36 68 73]


In [22]:
#Subtração
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([20,21,22,23,24,25])

arr = np.subtract(arr1,arr2)

print(arr)

[-10  -1   8  17  26  35]


In [23]:
#Multiplicação
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([20,21,22,23,24,25])

arr = np.multiply(arr1,arr2)
print(arr)

[ 200  420  660  920 1200 1500]


In [25]:
#Divisão
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([20,21,22,23,24,25])

arr = np.divide(arr1,arr2)
print(arr)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [27]:
#Média de uma coluna da tabela
#np.mean(df['coluna'])

#Soma de uma coluna da tabela
#np.sum(df['coluna'])

In [31]:
array = np.array([1,2,3,4,5,5,6,7,8,8,9,9])
#A partir da minha posição 5
result1 = np.minimum(array,5)

result2 = np.maximum(result1,0)

print(result2)

[1 2 3 4 5 5 5 5 5 5 5 5]


In [32]:
array = np.array([1,2,3,4,5,5,6,7,8,8,9,9])
#A partir da minha posição 5 substitua os demais dados por 7
array[array>5] = 7

print(array)

[1 2 3 4 5 5 7 7 7 7 7 7]
